language: c
os:
 - linux
compiler:
 - gcc
before_install:
 # remove binary
 - rm rpilogger/ads
 # Install necessary packages from apt-get
 - sudo apt-get install netcdf-bin
script:
 - cd rpilogger
 #- make -DCMAKE_BUILD_TYPE=Debug -DACADO_WITH_TESTING=ON ..
 - make ads
after_success:
 # Deploy the source code
 #- cd ..
 #- "./misc/deploy_code.sh"
 # Build the documentation and upload it to SF
 #- "./misc/publish_html.sh"
notifications:
# recipients:
#    - builds@acadotoolkit.org
  email:
    on_failure: always