language: c

os:
 - linux

compiler:
 - gcc

before_install:
 # remove binary
 - cd opendatalogger
 - make clean

 # Install necessary packages from apt-get
 - sudo apt-get update -qq
 - sudo apt-get install -y netcdf-bin libnetcdf-dev

script:
 - make all

after_success:
 # Deploy the source code
 # Build the documentation and upload it to SF

notifications:

email:
  on_failure: always
